=== ThePhen/stephens_experience_fun/basic_xsd_xslt_playground/more_about_stephen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/test"
	xmlns:tns="http://www.example.org/test" elementFormDefault="qualified">

    <element name="moreAboutStephen" type="tns:rootType">
    </element>

    <complexType name="rootType">
    	<sequence>
    		<element name="questions" type="tns:questionsType">
    		</element>
    	</sequence>
    	<attribute name="comment" use="required" type="string"/>
    </complexType>

    <complexType name="questionsType">
    	<sequence maxOccurs="unbounded">
    		<element name="question" type="tns:questionType" />
    	</sequence>
    </complexType>

	<complexType name="questionType">
		<sequence>
			<element name="body" type="string" />
			<element name="normalResponse" type="tns:normalResponse"
				minOccurs="0" maxOccurs="unbounded" />
			<element name="subdividedResponse"
				type="tns:subdividedResponse" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="id" type="long" use="required"/>
	</complexType>
    
    <complexType name="normalResponse">
    	<sequence>
    		<element name="subResponse" type="string"
					 maxOccurs="unbounded" />
    	</sequence>
    	<attribute name="earliestYear" use="required" type="tns:yearType" />
    	<attribute name="latestYear" use="required" type="tns:yearType" />
    </complexType>

    <complexType name="subdividedResponse">
    	<sequence>
    		<element name="subTopic" type="tns:subTopicType" maxOccurs="unbounded"/>
    	</sequence>
    </complexType>
    
    <complexType name="subTopicType">
    	<sequence>
    		<element name="subResponse" type="string"
					 maxOccurs="unbounded" />
    	</sequence>
    	<attribute name="title" type="string" />
    	<attribute name="earliestYear" use="required" type="tns:yearType" />
    	<attribute name="latestYear" use="required" type="tns:yearType" />
     </complexType>

	<simpleType name="yearType">
		<restriction base="string">
			<pattern value="\d{4}"/>
		</restriction>
	</simpleType>

</schema>

=== ThePhen/stephens_experience_fun/basic_xsd_xslt_playground/tiny_movies_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<moreAboutStephen comment="test"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/test more_about_stephen.xsd"
	xmlns="http://www.example.org/test">
	<questions>
		<question id="1">
			<body>What are your favorite colors?</body>
			<normalResponse earliestYear="1971" latestYear="2035">
				<subResponse>red</subResponse>
				<subResponse>green</subResponse>
				<subResponse>blue</subResponse>
			</normalResponse>
		</question>
		<question id="2">
			<body>What are your favorite movies by genre?</body>
			<subdividedResponse>
				<subTopic title="scifi" earliestYear="1977"
					latestYear="2003">
					<subResponse>Star Wars, Episode 3</subResponse>
					<subResponse>Star Ware, Episode 4</subResponse>
					<subResponse>Serenity</subResponse>
				</subTopic>
				<subTopic title="drama" earliestYear="1989"
					latestYear="2023">
					<subResponse>Steel Magnolias</subResponse>
					<subResponse>The English Patient</subResponse>
					<subResponse>Otto</subResponse>
				</subTopic>
				<subTopic title="comedy" earliestYear="1986"
					latestYear="2023">
					<subResponse>Big</subResponse>
					<subResponse>Four Weddings and a Funeral</subResponse>
					<subResponse>Challengers</subResponse>
				</subTopic>
			</subdividedResponse>
		</question>
	</questions>
</moreAboutStephen>
